export type rectPay = {
    is: rect,
    x: number,
    y: number,
    zIndex: number,
    width: number,
    height: number,
    text: string,
    color: string,
    borderRadius: number,
    scaleIn: number,
    radius: number,
    radiusPercent: number,
    transitions: Record<string, [number, number, number, number, number, number?]>,
    centered: boolean,
    borderWidth: number,
    borderColor: number,
    borderStyle: 'solid' | 'dashed',
    opacity: number,
    scale: number,
    rotate: number,
    fontFamily: string,
}
